[theme]
base = "light"
primaryColor = "#3498db"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"
font = "Poppins"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false